# -*- coding: utf-8 -*-
"""Data_visulization_linegraph&histogram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15FyGF05bSTWQlidtW2iAGoIQDrAi2tvo
"""

# Data visulization- in this we have to visulize data in graphical form
#We will be use three types of data for visulization- Iris dataset,Tips dataset,Titanic dataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snr
iris=snr.load_dataset('iris')#load_dataset()- use for load and read the data, We load the iris dataset for visulzation
iris.head()

data=iris.drop(['species'],axis=1)#axis=1 for select column and axis=0 for select the row
data.info()

# Line Graph: Data visulizartion by line graph
ax=data.plot(figsize=(15,7),title="Isis Dataset")# plot()-use for plot the graph, figsize- figure size,title- title showing on graph
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')

# Histogram: use for visulization of data by histogram graph
data['sepal_length'].diff().plot(kind='hist', bins=150,title='Sepal_Length')# bins defined the width of each histogram block

data['sepal_width'].diff().plot(kind='hist',bins=150,title="Sepal_width")

data['petal_length'].diff().plot(kind='hist',bins=150,title='Petal_Length')

data['petal_width'].diff().plot(kind='hist',bins=150,title="Petal_width")