# -*- coding: utf-8 -*-
"""pie_chart&scatter_plot&BarGraph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AKFK84qbeySS0_ifNZWfyBUR6Cywvm_C
"""

# Data visulization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snr
iris=snr.load_dataset('iris')
iris.head()

data=iris.drop(['species'],axis=1)
data.head()

# Data visulization by pie chart
data.iloc[0].plot.pie(figsize=(10,5),fontsize=10,autopct='%.2f')#pie chart for a single row 0

data.iloc[1:4].plot.pie(figsize=(10,10),subplots=True,fontsize=10,autopct='%.2f')#pie chart for rows 1,2,3, subplot-

data.iloc[0:].plot.pie(subplots=True,figsize=(5,5),autopct="%.2f")

# Scatter plot- comparing two parameter of your dataset use scatter plot, but not only two parameter maximum 3-parameters will campair possible
data.plot.scatter(x='sepal_length',y='petal_length',c='g')

data.plot.scatter(x='petal_length',y='petal_width',c='sepal_width')

data.iloc[0:5].plot(kind='bar',figsize=(10,5),title='Bar Graph')
