# -*- coding: utf-8 -*-
"""relational_plot&catplot&boxplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oacU2g3ExZIypDxYbyjVhdWUJVf3W_vm
"""

# Data visulization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as srn
tips=srn.load_dataset('tips')
tips.head()

# Relational Plot- is use to compare more then three feature/parameter of a dataset, as in scatter plot we have been compare maximum three features at a time
srn.relplot(data=tips,x='total_bill',y='tip',hue='smoker',)

srn.relplot(data=tips,x='total_bill',y='tip',hue='smoker',col='sex',style='day')

# Cat plot:It comparing two parameter only
srn.catplot(x='total_bill',y='sex',data=tips)

# Box Plot:-
srn.catplot(data=tips,x='total_bill',y='tip',hue='sex',kind='box')

# Pair Plot:
srn.pairplot(data=tips,x_vars=['tip','sex','smoker'],y_vars=['total_bill'],size=5)

